### ISSUE TITLE
Math characters not properly displayed 

### ISSUE THREAD

**Issue by SilviaLauraPintea** [BenTearzz/RemarkPortable#1]
![issue](https://user-images.githubusercontent.com/386361/69153346-5e570480-0ade-11ea-8ddb-88937e2d56e0.png)
Hi,

I really appreciate the portable template, however there seems to be a problem with nicely displaying some formulas. 

For example: 

``
\\( \bar{x} \\) or \\( \hat{x} \\) 
``
display the symbols above x, too high up. 

Is this fixable?
Cheers,
Silvia

**Comment by benstigsen** [comment]
I'm not sure if it's something on my end, something wrong with MathJax or something on your end, but your equation seems to work totally fine for me.

![image](https://user-images.githubusercontent.com/24865450/69152337-8e050d00-0adc-11ea-89bd-7ea1198b7965.png)

**Comment by SilviaLauraPintea** [comment]
It may be something on my side, although I tried it both in Chrome and Firefox and I still get the same issue.

Thank you for your reply, nonetheless.  
~S
