### ISSUE TITLE
Seems like the CSS link is wrong

### ISSUE THREAD

**Issue by ElTrasho3000** [BenTearzz/RemarkPortable#5]
I wondered why my changes in style.css didn't take effect. Changing the link in index.html did the job.
So instead of this:
```
<link rel="stylesheet" type="text/css" href="style.css"/>
```
that:
```
<link rel="stylesheet" type="text/css" href="./assets/style/style.css"/>
```

But overall a great project, thank you for making the effort!

**Comment by ElTrasho3000** [comment]
Also fonts in style.css need to be addressed llike this with the current directory tree:
```
@font-face{
  font-family: 'Droid Serif';
  src: url('../fonts/DroidSerif.ttf');
}

@font-face{
  font-family: 'Yanone Kaffeesatz';
  src: url('../fonts/YanoneKaffeesatz.otf');
}

@font-face{
  font-family: 'Ubuntu Mono';
  src: url('../fonts/UbuntuMono.ttf');
}
```

**Comment by benstigsen** [comment]
Yes, thank you very much for pointing it out!
I didn't have a lot of experience when I first created this project. I'd like to create something similar to this, but with a way _simpler_ and _smaller_ codebase.

**Comment by ElTrasho3000** [comment]
Sounds good to me. I don't have much experience with JS yet. But if you wan't to collaborate on this, let me know. 
I'm not entirely happy with the available md to presentation tools and already thought about writing my own.
